// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.1
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#include "ui.h"

lv_obj_t * ui_Screen8 = NULL;
lv_obj_t * ui_Version_Heading = NULL;
lv_obj_t * ui_cancelButton = NULL;
lv_obj_t * ui_cancelText = NULL;
lv_obj_t * ui_confirmButton = NULL;
lv_obj_t * ui_confirmText = NULL;
lv_obj_t * ui_currentVersionText = NULL;
lv_obj_t * ui_latestVersionText = NULL;
lv_obj_t * ui_currentVersionNumber = NULL;
lv_obj_t * ui_latestVersionNumber = NULL;
lv_obj_t * ui_Popup1 = NULL;
lv_obj_t * ui_UpgradingTextPopUp = NULL;
lv_obj_t * ui_upgradeProgressBarPopUp = NULL;
lv_obj_t * ui_Popup2 = NULL;
// event funtions
void ui_event_Screen8(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_GESTURE &&  lv_indev_get_gesture_dir(lv_indev_get_act()) == LV_DIR_RIGHT) {
        lv_indev_wait_release(lv_indev_get_act());
        _ui_screen_change(&ui_Screen7, LV_SCR_LOAD_ANIM_NONE, 20, 0, &ui_Screen7_screen_init);
    }
}

void ui_event_cancelButton(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_RELEASED) {
        _ui_screen_change(&ui_Screen1, LV_SCR_LOAD_ANIM_NONE, 20, 0, &ui_Screen1_screen_init);
    }
}

void ui_event_confirmButton(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_RELEASED) {
        _ui_opacity_set(ui_Popup1, 255);
    }
}

// build funtions

void ui_Screen8_screen_init(void)
{
    ui_Screen8 = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_Screen8, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Version_Heading = lv_label_create(ui_Screen8);
    lv_obj_set_width(ui_Version_Heading, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Version_Heading, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Version_Heading, -1);
    lv_obj_set_y(ui_Version_Heading, -75);
    lv_obj_set_align(ui_Version_Heading, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Version_Heading, "VERSION");
    lv_obj_set_style_text_color(ui_Version_Heading, lv_color_hex(0x95FF38), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Version_Heading, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Version_Heading, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_cancelButton = lv_btn_create(ui_Screen8);
    lv_obj_set_width(ui_cancelButton, 61);
    lv_obj_set_height(ui_cancelButton, 29);
    lv_obj_set_x(ui_cancelButton, -40);
    lv_obj_set_y(ui_cancelButton, 72);
    lv_obj_set_align(ui_cancelButton, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_cancelButton, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_cancelButton, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_cancelButton, lv_color_hex(0x9A0101), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_cancelButton, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_cancelText = lv_label_create(ui_cancelButton);
    lv_obj_set_width(ui_cancelText, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_cancelText, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_cancelText, LV_ALIGN_CENTER);
    lv_label_set_text(ui_cancelText, "Cancel");
    lv_obj_set_style_text_font(ui_cancelText, &lv_font_montserrat_12, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_confirmButton = lv_btn_create(ui_Screen8);
    lv_obj_set_width(ui_confirmButton, 61);
    lv_obj_set_height(ui_confirmButton, 29);
    lv_obj_set_x(ui_confirmButton, 40);
    lv_obj_set_y(ui_confirmButton, 72);
    lv_obj_set_align(ui_confirmButton, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_confirmButton, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_confirmButton, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_confirmButton, lv_color_hex(0x6C6D6B), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_confirmButton, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_confirmText = lv_label_create(ui_confirmButton);
    lv_obj_set_width(ui_confirmText, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_confirmText, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_confirmText, LV_ALIGN_CENTER);
    lv_label_set_text(ui_confirmText, "Confirm");
    lv_obj_set_style_text_font(ui_confirmText, &lv_font_montserrat_12, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_currentVersionText = lv_label_create(ui_Screen8);
    lv_obj_set_width(ui_currentVersionText, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_currentVersionText, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_currentVersionText, -23);
    lv_obj_set_y(ui_currentVersionText, -13);
    lv_obj_set_align(ui_currentVersionText, LV_ALIGN_CENTER);
    lv_label_set_text(ui_currentVersionText, "Current Version - ");
    lv_obj_set_style_text_font(ui_currentVersionText, &lv_font_montserrat_14, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_latestVersionText = lv_label_create(ui_Screen8);
    lv_obj_set_width(ui_latestVersionText, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_latestVersionText, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_latestVersionText, -17);
    lv_obj_set_y(ui_latestVersionText, 13);
    lv_obj_set_align(ui_latestVersionText, LV_ALIGN_CENTER);
    lv_label_set_text(ui_latestVersionText, "Latest Version - ");
    lv_obj_set_style_text_font(ui_latestVersionText, &lv_font_montserrat_14, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_currentVersionNumber = lv_label_create(ui_Screen8);
    lv_obj_set_width(ui_currentVersionNumber, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_currentVersionNumber, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_currentVersionNumber, 60);
    lv_obj_set_y(ui_currentVersionNumber, -13);
    lv_obj_set_align(ui_currentVersionNumber, LV_ALIGN_CENTER);
    lv_label_set_text(ui_currentVersionNumber, "1.0.0");

    ui_latestVersionNumber = lv_label_create(ui_Screen8);
    lv_obj_set_width(ui_latestVersionNumber, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_latestVersionNumber, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_latestVersionNumber, 60);
    lv_obj_set_y(ui_latestVersionNumber, 13);
    lv_obj_set_align(ui_latestVersionNumber, LV_ALIGN_CENTER);
    lv_label_set_text(ui_latestVersionNumber, "1.0.3");

    ui_Popup1 = lv_obj_create(ui_Screen8);
    lv_obj_remove_style_all(ui_Popup1);
    lv_obj_set_width(ui_Popup1, 245);
    lv_obj_set_height(ui_Popup1, 259);
    lv_obj_set_align(ui_Popup1, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Popup1, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_Popup1, 15, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Popup1, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Popup1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_blend_mode(ui_Popup1, LV_BLEND_MODE_NORMAL, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_opa(ui_Popup1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_UpgradingTextPopUp = lv_label_create(ui_Popup1);
    lv_obj_set_width(ui_UpgradingTextPopUp, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_UpgradingTextPopUp, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_UpgradingTextPopUp, 0);
    lv_obj_set_y(ui_UpgradingTextPopUp, -10);
    lv_obj_set_align(ui_UpgradingTextPopUp, LV_ALIGN_CENTER);
    lv_label_set_text(ui_UpgradingTextPopUp, "UPGRADING");
    lv_obj_set_style_text_color(ui_UpgradingTextPopUp, lv_color_hex(0xE40001), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_UpgradingTextPopUp, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_UpgradingTextPopUp, &lv_font_montserrat_12, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_upgradeProgressBarPopUp = lv_slider_create(ui_Popup1);
    lv_slider_set_value(ui_upgradeProgressBarPopUp, 0, LV_ANIM_OFF);
    if(lv_slider_get_mode(ui_upgradeProgressBarPopUp) == LV_SLIDER_MODE_RANGE) lv_slider_set_left_value(
            ui_upgradeProgressBarPopUp, 0, LV_ANIM_OFF);
    lv_obj_set_width(ui_upgradeProgressBarPopUp, 155);
    lv_obj_set_height(ui_upgradeProgressBarPopUp, 5);
    lv_obj_set_x(ui_upgradeProgressBarPopUp, 0);
    lv_obj_set_y(ui_upgradeProgressBarPopUp, 5);
    lv_obj_set_align(ui_upgradeProgressBarPopUp, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_upgradeProgressBarPopUp,
                      LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_SCROLLABLE |
                      LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM | LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags
    lv_obj_set_style_bg_color(ui_upgradeProgressBarPopUp, lv_color_hex(0x525252), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_upgradeProgressBarPopUp, 150, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_color(ui_upgradeProgressBarPopUp, lv_color_hex(0xE40001), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_upgradeProgressBarPopUp, 255, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_color(ui_upgradeProgressBarPopUp, lv_color_hex(0xFFFFFF), LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_upgradeProgressBarPopUp, 0, LV_PART_KNOB | LV_STATE_DEFAULT);

    ui_Popup2 = lv_obj_create(ui_Screen8);
    lv_obj_remove_style_all(ui_Popup2);
    lv_obj_set_width(ui_Popup2, 245);
    lv_obj_set_height(ui_Popup2, 259);
    lv_obj_set_align(ui_Popup2, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Popup2, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_Popup2, 15, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Popup2, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Popup2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_blend_mode(ui_Popup2, LV_BLEND_MODE_NORMAL, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_opa(ui_Popup2, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_add_event_cb(ui_cancelButton, ui_event_cancelButton, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_confirmButton, ui_event_confirmButton, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Screen8, ui_event_Screen8, LV_EVENT_ALL, NULL);

}

void ui_Screen8_screen_destroy(void)
{
    if(ui_Screen8) lv_obj_del(ui_Screen8);

    // NULL screen variables
    ui_Screen8 = NULL;
    ui_Version_Heading = NULL;
    ui_cancelButton = NULL;
    ui_cancelText = NULL;
    ui_confirmButton = NULL;
    ui_confirmText = NULL;
    ui_currentVersionText = NULL;
    ui_latestVersionText = NULL;
    ui_currentVersionNumber = NULL;
    ui_latestVersionNumber = NULL;
    ui_Popup1 = NULL;
    ui_UpgradingTextPopUp = NULL;
    ui_upgradeProgressBarPopUp = NULL;
    ui_Popup2 = NULL;

}
