// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.1
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#ifndef UI_SCREEN8_H
#define UI_SCREEN8_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_Screen8
extern void ui_Screen8_screen_init(void);
extern void ui_Screen8_screen_destroy(void);
extern void ui_event_Screen8(lv_event_t * e);
extern lv_obj_t * ui_Screen8;
extern lv_obj_t * ui_Version_Heading;
extern void ui_event_cancelButton(lv_event_t * e);
extern lv_obj_t * ui_cancelButton;
extern lv_obj_t * ui_cancelText;
extern void ui_event_confirmButton(lv_event_t * e);
extern lv_obj_t * ui_confirmButton;
extern lv_obj_t * ui_confirmText;
extern lv_obj_t * ui_currentVersionText;
extern lv_obj_t * ui_latestVersionText;
extern lv_obj_t * ui_currentVersionNumber;
extern lv_obj_t * ui_latestVersionNumber;
extern lv_obj_t * ui_Popup1;
extern lv_obj_t * ui_UpgradingTextPopUp;
extern lv_obj_t * ui_upgradeProgressBarPopUp;
extern lv_obj_t * ui_Popup2;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

