// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.1
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#include "ui.h"

lv_obj_t * ui_Screen3 = NULL;
lv_obj_t * ui_SpO2Live = NULL;
lv_obj_t * ui_buttonSpO2 = NULL;
lv_obj_t * ui_StartMeasure3 = NULL;
lv_obj_t * ui_Screen3_Heading = NULL;
// event funtions
void ui_event_Screen3(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_GESTURE &&  lv_indev_get_gesture_dir(lv_indev_get_act()) == LV_DIR_BOTTOM) {
        lv_indev_wait_release(lv_indev_get_act());
        _ui_screen_change(&ui_Screen2, LV_SCR_LOAD_ANIM_NONE, 20, 0, &ui_Screen2_screen_init);
    }
    if(event_code == LV_EVENT_GESTURE &&  lv_indev_get_gesture_dir(lv_indev_get_act()) == LV_DIR_TOP) {
        lv_indev_wait_release(lv_indev_get_act());
        _ui_screen_change(&ui_Screen4, LV_SCR_LOAD_ANIM_NONE, 20, 0, &ui_Screen4_screen_init);
    }
    if(event_code == LV_EVENT_GESTURE &&  lv_indev_get_gesture_dir(lv_indev_get_act()) == LV_DIR_RIGHT) {
        lv_indev_wait_release(lv_indev_get_act());
        _ui_screen_change(&ui_Screen1, LV_SCR_LOAD_ANIM_NONE, 20, 0, &ui_Screen1_screen_init);
    }
}

void ui_event_buttonSpO2(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);

    if(event_code == LV_EVENT_RELEASED) {
        _ui_checked_set_text_value(ui_StartMeasure2, target, "", "");
    }
}

// build funtions

void ui_Screen3_screen_init(void)
{
    ui_Screen3 = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_Screen3, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_SpO2Live = lv_label_create(ui_Screen3);
    lv_obj_set_width(ui_SpO2Live, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_SpO2Live, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_SpO2Live, 35);
    lv_obj_set_y(ui_SpO2Live, -10);
    lv_obj_set_align(ui_SpO2Live, LV_ALIGN_CENTER);
    lv_label_set_text(ui_SpO2Live, "98%");
    lv_obj_set_style_text_font(ui_SpO2Live, &lv_font_montserrat_24, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_buttonSpO2 = lv_btn_create(ui_Screen3);
    lv_obj_set_width(ui_buttonSpO2, 100);
    lv_obj_set_height(ui_buttonSpO2, 50);
    lv_obj_set_x(ui_buttonSpO2, 0);
    lv_obj_set_y(ui_buttonSpO2, 67);
    lv_obj_set_align(ui_buttonSpO2, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_buttonSpO2, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_buttonSpO2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_buttonSpO2, lv_color_hex(0x199010), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_buttonSpO2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_StartMeasure3 = lv_label_create(ui_buttonSpO2);
    lv_obj_set_width(ui_StartMeasure3, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_StartMeasure3, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_StartMeasure3, LV_ALIGN_CENTER);
    lv_label_set_text(ui_StartMeasure3, "Start\nMeasuring");
    lv_obj_set_style_text_align(ui_StartMeasure3, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Screen3_Heading = lv_label_create(ui_Screen3);
    lv_obj_set_width(ui_Screen3_Heading, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Screen3_Heading, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Screen3_Heading, 0);
    lv_obj_set_y(ui_Screen3_Heading, -75);
    lv_obj_set_align(ui_Screen3_Heading, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Screen3_Heading, "SpO2");
    lv_obj_set_style_text_font(ui_Screen3_Heading, &lv_font_montserrat_22, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_add_event_cb(ui_buttonSpO2, ui_event_buttonSpO2, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Screen3, ui_event_Screen3, LV_EVENT_ALL, NULL);

}

void ui_Screen3_screen_destroy(void)
{
    if(ui_Screen3) lv_obj_del(ui_Screen3);

    // NULL screen variables
    ui_Screen3 = NULL;
    ui_SpO2Live = NULL;
    ui_buttonSpO2 = NULL;
    ui_StartMeasure3 = NULL;
    ui_Screen3_Heading = NULL;

}
