// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.1
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#include "ui.h"

lv_obj_t * ui_Screen7 = NULL;
lv_obj_t * ui_WarningText = NULL;
lv_obj_t * ui_Warning_Heading = NULL;
lv_obj_t * ui_ButtonUpgradeFinal = NULL;
lv_obj_t * ui_UpgradeTextFinal = NULL;
// event funtions
void ui_event_Screen7(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_GESTURE &&  lv_indev_get_gesture_dir(lv_indev_get_act()) == LV_DIR_RIGHT) {
        lv_indev_wait_release(lv_indev_get_act());
        _ui_screen_change(&ui_Screen6, LV_SCR_LOAD_ANIM_NONE, 20, 0, &ui_Screen6_screen_init);
    }
}

// build funtions

void ui_Screen7_screen_init(void)
{
    ui_Screen7 = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_Screen7, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_WarningText = lv_textarea_create(ui_Screen7);
    lv_obj_set_width(ui_WarningText, 183);
    lv_obj_set_height(ui_WarningText, 124);
    lv_obj_set_align(ui_WarningText, LV_ALIGN_CENTER);
    lv_textarea_set_text(ui_WarningText,
                         "Please connect the charger to the watch and ensure a stable Wi-Fi connection is maintained throughout the upgrade process. Do not turn off the watch or interrupt the upgrade process.");
    lv_textarea_set_placeholder_text(ui_WarningText, "Placeholder...");
    lv_obj_set_style_text_color(ui_WarningText, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_WarningText, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_WarningText, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_WarningText, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_WarningText, lv_color_hex(0x5C5C5C), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_WarningText, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_WarningText, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_side(ui_WarningText, LV_BORDER_SIDE_FULL, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Warning_Heading = lv_label_create(ui_Screen7);
    lv_obj_set_width(ui_Warning_Heading, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Warning_Heading, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Warning_Heading, 0);
    lv_obj_set_y(ui_Warning_Heading, -80);
    lv_obj_set_align(ui_Warning_Heading, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Warning_Heading, "WARNING");
    lv_obj_set_style_text_color(ui_Warning_Heading, lv_color_hex(0xD30000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Warning_Heading, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Warning_Heading, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ButtonUpgradeFinal = lv_btn_create(ui_Screen7);
    lv_obj_set_width(ui_ButtonUpgradeFinal, 100);
    lv_obj_set_height(ui_ButtonUpgradeFinal, 27);
    lv_obj_set_x(ui_ButtonUpgradeFinal, 0);
    lv_obj_set_y(ui_ButtonUpgradeFinal, 90);
    lv_obj_set_align(ui_ButtonUpgradeFinal, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_ButtonUpgradeFinal, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_ButtonUpgradeFinal, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_ButtonUpgradeFinal, lv_color_hex(0x424242), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_ButtonUpgradeFinal, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_UpgradeTextFinal = lv_label_create(ui_ButtonUpgradeFinal);
    lv_obj_set_width(ui_UpgradeTextFinal, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_UpgradeTextFinal, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_UpgradeTextFinal, LV_ALIGN_CENTER);
    lv_label_set_text(ui_UpgradeTextFinal, "Upgrade");

    lv_obj_add_event_cb(ui_Screen7, ui_event_Screen7, LV_EVENT_ALL, NULL);

}

void ui_Screen7_screen_destroy(void)
{
    if(ui_Screen7) lv_obj_del(ui_Screen7);

    // NULL screen variables
    ui_Screen7 = NULL;
    ui_WarningText = NULL;
    ui_Warning_Heading = NULL;
    ui_ButtonUpgradeFinal = NULL;
    ui_UpgradeTextFinal = NULL;

}
