// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.1
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#include "ui.h"

lv_obj_t * ui_Screen5 = NULL;
lv_obj_t * ui_buttonTemp = NULL;
lv_obj_t * ui_StartMeasure5 = NULL;
lv_obj_t * ui_humLive = NULL;
lv_obj_t * ui_Screen5_Heading = NULL;
lv_obj_t * ui_temp_label = NULL;
lv_obj_t * ui_hum_label = NULL;
lv_obj_t * ui_tempLive = NULL;
// event funtions
void ui_event_Screen5(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_GESTURE &&  lv_indev_get_gesture_dir(lv_indev_get_act()) == LV_DIR_TOP) {
        lv_indev_wait_release(lv_indev_get_act());
        _ui_screen_change(&ui_Screen6, LV_SCR_LOAD_ANIM_NONE, 20, 0, &ui_Screen6_screen_init);
    }
    if(event_code == LV_EVENT_GESTURE &&  lv_indev_get_gesture_dir(lv_indev_get_act()) == LV_DIR_BOTTOM) {
        lv_indev_wait_release(lv_indev_get_act());
        _ui_screen_change(&ui_Screen4, LV_SCR_LOAD_ANIM_NONE, 20, 0, &ui_Screen4_screen_init);
    }
    if(event_code == LV_EVENT_GESTURE &&  lv_indev_get_gesture_dir(lv_indev_get_act()) == LV_DIR_RIGHT) {
        lv_indev_wait_release(lv_indev_get_act());
        _ui_screen_change(&ui_Screen1, LV_SCR_LOAD_ANIM_NONE, 20, 0, &ui_Screen1_screen_init);
    }
}

// build funtions

void ui_Screen5_screen_init(void)
{
    ui_Screen5 = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_Screen5, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_buttonTemp = lv_btn_create(ui_Screen5);
    lv_obj_set_width(ui_buttonTemp, 100);
    lv_obj_set_height(ui_buttonTemp, 50);
    lv_obj_set_x(ui_buttonTemp, 0);
    lv_obj_set_y(ui_buttonTemp, 67);
    lv_obj_set_align(ui_buttonTemp, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_buttonTemp, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_buttonTemp, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_buttonTemp, lv_color_hex(0xB25100), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_buttonTemp, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_StartMeasure5 = lv_label_create(ui_buttonTemp);
    lv_obj_set_width(ui_StartMeasure5, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_StartMeasure5, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_StartMeasure5, LV_ALIGN_CENTER);
    lv_label_set_text(ui_StartMeasure5, "Start\nMeasuring");
    lv_obj_set_style_text_align(ui_StartMeasure5, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_humLive = lv_label_create(ui_Screen5);
    lv_obj_set_width(ui_humLive, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_humLive, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_humLive, 29);
    lv_obj_set_y(ui_humLive, 15);
    lv_obj_set_align(ui_humLive, LV_ALIGN_CENTER);
    lv_label_set_text(ui_humLive, "75%");
    lv_obj_set_style_text_font(ui_humLive, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Screen5_Heading = lv_label_create(ui_Screen5);
    lv_obj_set_width(ui_Screen5_Heading, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Screen5_Heading, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Screen5_Heading, 0);
    lv_obj_set_y(ui_Screen5_Heading, -65);
    lv_obj_set_align(ui_Screen5_Heading, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Screen5_Heading, "TEMPERATURE\nHUMIDITY");
    lv_obj_set_style_text_align(ui_Screen5_Heading, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Screen5_Heading, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_temp_label = lv_label_create(ui_Screen5);
    lv_obj_set_width(ui_temp_label, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_temp_label, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_temp_label, -39);
    lv_obj_set_y(ui_temp_label, -14);
    lv_obj_set_align(ui_temp_label, LV_ALIGN_CENTER);
    lv_label_set_text(ui_temp_label, "TEMP");

    ui_hum_label = lv_label_create(ui_Screen5);
    lv_obj_set_width(ui_hum_label, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_hum_label, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_hum_label, -39);
    lv_obj_set_y(ui_hum_label, 15);
    lv_obj_set_align(ui_hum_label, LV_ALIGN_CENTER);
    lv_label_set_text(ui_hum_label, "HUM");

    ui_tempLive = lv_label_create(ui_Screen5);
    lv_obj_set_width(ui_tempLive, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_tempLive, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_tempLive, 29);
    lv_obj_set_y(ui_tempLive, -14);
    lv_obj_set_align(ui_tempLive, LV_ALIGN_CENTER);
    lv_label_set_text(ui_tempLive, "28°C");
    lv_obj_set_style_text_font(ui_tempLive, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_add_event_cb(ui_Screen5, ui_event_Screen5, LV_EVENT_ALL, NULL);

}

void ui_Screen5_screen_destroy(void)
{
    if(ui_Screen5) lv_obj_del(ui_Screen5);

    // NULL screen variables
    ui_Screen5 = NULL;
    ui_buttonTemp = NULL;
    ui_StartMeasure5 = NULL;
    ui_humLive = NULL;
    ui_Screen5_Heading = NULL;
    ui_temp_label = NULL;
    ui_hum_label = NULL;
    ui_tempLive = NULL;

}
