// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.1
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#include "ui.h"

lv_obj_t * ui_Screen6 = NULL;
lv_obj_t * ui_wifiSwitch = NULL;
lv_obj_t * ui_bleSwitch = NULL;
lv_obj_t * ui_ButtonSyncNow = NULL;
lv_obj_t * ui_SyncNowText = NULL;
lv_obj_t * ui_ButtonUpgrade = NULL;
lv_obj_t * ui_UpgradeText = NULL;
lv_obj_t * ui_WIFI = NULL;
lv_obj_t * ui_BLUETOOTH = NULL;
// event funtions
void ui_event_Screen6(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_GESTURE &&  lv_indev_get_gesture_dir(lv_indev_get_act()) == LV_DIR_TOP) {
        lv_indev_wait_release(lv_indev_get_act());
        _ui_screen_change(&ui_Screen1, LV_SCR_LOAD_ANIM_NONE, 20, 0, &ui_Screen1_screen_init);
    }
    if(event_code == LV_EVENT_GESTURE &&  lv_indev_get_gesture_dir(lv_indev_get_act()) == LV_DIR_BOTTOM) {
        lv_indev_wait_release(lv_indev_get_act());
        _ui_screen_change(&ui_Screen5, LV_SCR_LOAD_ANIM_NONE, 20, 0, &ui_Screen5_screen_init);
    }
    if(event_code == LV_EVENT_GESTURE &&  lv_indev_get_gesture_dir(lv_indev_get_act()) == LV_DIR_RIGHT) {
        lv_indev_wait_release(lv_indev_get_act());
        _ui_screen_change(&ui_Screen1, LV_SCR_LOAD_ANIM_NONE, 20, 0, &ui_Screen1_screen_init);
    }
}

void ui_event_ButtonUpgrade(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_RELEASED) {
        _ui_screen_change(&ui_Screen7, LV_SCR_LOAD_ANIM_NONE, 20, 0, &ui_Screen7_screen_init);
    }
}

// build funtions

void ui_Screen6_screen_init(void)
{
    ui_Screen6 = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_Screen6, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_wifiSwitch = lv_switch_create(ui_Screen6);
    lv_obj_set_width(ui_wifiSwitch, 50);
    lv_obj_set_height(ui_wifiSwitch, 25);
    lv_obj_set_x(ui_wifiSwitch, 33);
    lv_obj_set_y(ui_wifiSwitch, -70);
    lv_obj_set_align(ui_wifiSwitch, LV_ALIGN_CENTER);

    ui_bleSwitch = lv_switch_create(ui_Screen6);
    lv_obj_set_width(ui_bleSwitch, 50);
    lv_obj_set_height(ui_bleSwitch, 25);
    lv_obj_set_x(ui_bleSwitch, 33);
    lv_obj_set_y(ui_bleSwitch, -20);
    lv_obj_set_align(ui_bleSwitch, LV_ALIGN_CENTER);

    ui_ButtonSyncNow = lv_btn_create(ui_Screen6);
    lv_obj_set_width(ui_ButtonSyncNow, 100);
    lv_obj_set_height(ui_ButtonSyncNow, 39);
    lv_obj_set_x(ui_ButtonSyncNow, 0);
    lv_obj_set_y(ui_ButtonSyncNow, 30);
    lv_obj_set_align(ui_ButtonSyncNow, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_ButtonSyncNow, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_ButtonSyncNow, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_ButtonSyncNow, lv_color_hex(0x0F9900), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_ButtonSyncNow, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_SyncNowText = lv_label_create(ui_ButtonSyncNow);
    lv_obj_set_width(ui_SyncNowText, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_SyncNowText, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_SyncNowText, LV_ALIGN_CENTER);
    lv_label_set_text(ui_SyncNowText, "SYNC NOW");

    ui_ButtonUpgrade = lv_btn_create(ui_Screen6);
    lv_obj_set_width(ui_ButtonUpgrade, 100);
    lv_obj_set_height(ui_ButtonUpgrade, 25);
    lv_obj_set_x(ui_ButtonUpgrade, 0);
    lv_obj_set_y(ui_ButtonUpgrade, 80);
    lv_obj_set_align(ui_ButtonUpgrade, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_ButtonUpgrade, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_ButtonUpgrade, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_ButtonUpgrade, lv_color_hex(0x990000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_ButtonUpgrade, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_UpgradeText = lv_label_create(ui_ButtonUpgrade);
    lv_obj_set_width(ui_UpgradeText, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_UpgradeText, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_UpgradeText, LV_ALIGN_CENTER);
    lv_label_set_text(ui_UpgradeText, "UPGRADE");

    ui_WIFI = lv_label_create(ui_Screen6);
    lv_obj_set_width(ui_WIFI, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_WIFI, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_WIFI, -35);
    lv_obj_set_y(ui_WIFI, -70);
    lv_obj_set_align(ui_WIFI, LV_ALIGN_CENTER);
    lv_label_set_text(ui_WIFI, "WIFI");
    lv_obj_set_style_text_color(ui_WIFI, lv_color_hex(0xB0B0B0), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_WIFI, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_WIFI, &lv_font_montserrat_26, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_BLUETOOTH = lv_label_create(ui_Screen6);
    lv_obj_set_width(ui_BLUETOOTH, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_BLUETOOTH, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_BLUETOOTH, -35);
    lv_obj_set_y(ui_BLUETOOTH, -20);
    lv_obj_set_align(ui_BLUETOOTH, LV_ALIGN_CENTER);
    lv_label_set_text(ui_BLUETOOTH, "BLE");
    lv_obj_set_style_text_color(ui_BLUETOOTH, lv_color_hex(0x4984FF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_BLUETOOTH, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_BLUETOOTH, &lv_font_montserrat_26, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_add_event_cb(ui_ButtonUpgrade, ui_event_ButtonUpgrade, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Screen6, ui_event_Screen6, LV_EVENT_ALL, NULL);

}

void ui_Screen6_screen_destroy(void)
{
    if(ui_Screen6) lv_obj_del(ui_Screen6);

    // NULL screen variables
    ui_Screen6 = NULL;
    ui_wifiSwitch = NULL;
    ui_bleSwitch = NULL;
    ui_ButtonSyncNow = NULL;
    ui_SyncNowText = NULL;
    ui_ButtonUpgrade = NULL;
    ui_UpgradeText = NULL;
    ui_WIFI = NULL;
    ui_BLUETOOTH = NULL;

}
