// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.1
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#include "ui.h"

lv_obj_t * ui_Screen4 = NULL;
lv_obj_t * ui_buttonBP = NULL;
lv_obj_t * ui_StartMeasure4 = NULL;
lv_obj_t * ui_HeartImg2 = NULL;
lv_obj_t * ui_heartRateLiveBP = NULL;
lv_obj_t * ui_Screen4_Heading = NULL;
lv_obj_t * ui_dia_label = NULL;
lv_obj_t * ui_sys_label = NULL;
lv_obj_t * ui_diaLive = NULL;
lv_obj_t * ui_sysLive = NULL;
// event funtions
void ui_event_Screen4(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_GESTURE &&  lv_indev_get_gesture_dir(lv_indev_get_act()) == LV_DIR_TOP) {
        lv_indev_wait_release(lv_indev_get_act());
        _ui_screen_change(&ui_Screen5, LV_SCR_LOAD_ANIM_NONE, 20, 0, &ui_Screen5_screen_init);
    }
    if(event_code == LV_EVENT_GESTURE &&  lv_indev_get_gesture_dir(lv_indev_get_act()) == LV_DIR_BOTTOM) {
        lv_indev_wait_release(lv_indev_get_act());
        _ui_screen_change(&ui_Screen3, LV_SCR_LOAD_ANIM_NONE, 20, 0, &ui_Screen3_screen_init);
    }
    if(event_code == LV_EVENT_GESTURE &&  lv_indev_get_gesture_dir(lv_indev_get_act()) == LV_DIR_RIGHT) {
        lv_indev_wait_release(lv_indev_get_act());
        _ui_screen_change(&ui_Screen1, LV_SCR_LOAD_ANIM_NONE, 20, 0, &ui_Screen1_screen_init);
    }
}

// build funtions

void ui_Screen4_screen_init(void)
{
    ui_Screen4 = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_Screen4, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_buttonBP = lv_btn_create(ui_Screen4);
    lv_obj_set_width(ui_buttonBP, 100);
    lv_obj_set_height(ui_buttonBP, 50);
    lv_obj_set_x(ui_buttonBP, 0);
    lv_obj_set_y(ui_buttonBP, 67);
    lv_obj_set_align(ui_buttonBP, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_buttonBP, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_buttonBP, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_buttonBP, lv_color_hex(0x007E79), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_buttonBP, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_StartMeasure4 = lv_label_create(ui_buttonBP);
    lv_obj_set_width(ui_StartMeasure4, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_StartMeasure4, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_StartMeasure4, LV_ALIGN_CENTER);
    lv_label_set_text(ui_StartMeasure4, "Start\nMeasuring");
    lv_obj_set_style_text_align(ui_StartMeasure4, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_HeartImg2 = lv_img_create(ui_Screen4);
    lv_img_set_src(ui_HeartImg2, &ui_img_208041617);
    lv_obj_set_width(ui_HeartImg2, LV_SIZE_CONTENT);   /// 256
    lv_obj_set_height(ui_HeartImg2, LV_SIZE_CONTENT);    /// 256
    lv_obj_set_x(ui_HeartImg2, -45);
    lv_obj_set_y(ui_HeartImg2, 22);
    lv_obj_set_align(ui_HeartImg2, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_HeartImg2, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_HeartImg2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_img_set_zoom(ui_HeartImg2, 20);

    ui_heartRateLiveBP = lv_label_create(ui_Screen4);
    lv_obj_set_width(ui_heartRateLiveBP, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_heartRateLiveBP, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_heartRateLiveBP, 16);
    lv_obj_set_y(ui_heartRateLiveBP, 22);
    lv_obj_set_align(ui_heartRateLiveBP, LV_ALIGN_CENTER);
    lv_label_set_text(ui_heartRateLiveBP, "100 BPM");
    lv_obj_set_style_text_font(ui_heartRateLiveBP, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Screen4_Heading = lv_label_create(ui_Screen4);
    lv_obj_set_width(ui_Screen4_Heading, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Screen4_Heading, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Screen4_Heading, 0);
    lv_obj_set_y(ui_Screen4_Heading, -84);
    lv_obj_set_align(ui_Screen4_Heading, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Screen4_Heading, "BLOOD\nPRESSURE");
    lv_obj_set_style_text_align(ui_Screen4_Heading, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Screen4_Heading, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_dia_label = lv_label_create(ui_Screen4);
    lv_obj_set_width(ui_dia_label, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_dia_label, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_dia_label, -47);
    lv_obj_set_y(ui_dia_label, -5);
    lv_obj_set_align(ui_dia_label, LV_ALIGN_CENTER);
    lv_label_set_text(ui_dia_label, "DIA");

    ui_sys_label = lv_label_create(ui_Screen4);
    lv_obj_set_width(ui_sys_label, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_sys_label, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_sys_label, -50);
    lv_obj_set_y(ui_sys_label, -27);
    lv_obj_set_align(ui_sys_label, LV_ALIGN_CENTER);
    lv_label_set_text(ui_sys_label, "SYS");

    ui_diaLive = lv_label_create(ui_Screen4);
    lv_obj_set_width(ui_diaLive, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_diaLive, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_diaLive, 23);
    lv_obj_set_y(ui_diaLive, -5);
    lv_obj_set_align(ui_diaLive, LV_ALIGN_CENTER);
    lv_label_set_text(ui_diaLive, "80 mmHg");
    lv_obj_set_style_text_font(ui_diaLive, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_sysLive = lv_label_create(ui_Screen4);
    lv_obj_set_width(ui_sysLive, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_sysLive, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_sysLive, 25);
    lv_obj_set_y(ui_sysLive, -27);
    lv_obj_set_align(ui_sysLive, LV_ALIGN_CENTER);
    lv_label_set_text(ui_sysLive, "120 mmHg");
    lv_obj_set_style_text_font(ui_sysLive, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_add_event_cb(ui_Screen4, ui_event_Screen4, LV_EVENT_ALL, NULL);

}

void ui_Screen4_screen_destroy(void)
{
    if(ui_Screen4) lv_obj_del(ui_Screen4);

    // NULL screen variables
    ui_Screen4 = NULL;
    ui_buttonBP = NULL;
    ui_StartMeasure4 = NULL;
    ui_HeartImg2 = NULL;
    ui_heartRateLiveBP = NULL;
    ui_Screen4_Heading = NULL;
    ui_dia_label = NULL;
    ui_sys_label = NULL;
    ui_diaLive = NULL;
    ui_sysLive = NULL;

}
