// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.1
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#include "ui.h"

lv_obj_t * ui_Screen2 = NULL;
lv_obj_t * ui_buttonHeart = NULL;
lv_obj_t * ui_StartMeasure2 = NULL;
lv_obj_t * ui_heartImg1 = NULL;
lv_obj_t * ui_heartRateLive = NULL;
lv_obj_t * ui_Screen2_Heading = NULL;
// event funtions
void ui_event_Screen2(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_GESTURE &&  lv_indev_get_gesture_dir(lv_indev_get_act()) == LV_DIR_TOP) {
        lv_indev_wait_release(lv_indev_get_act());
        _ui_screen_change(&ui_Screen3, LV_SCR_LOAD_ANIM_NONE, 20, 0, &ui_Screen3_screen_init);
    }
    if(event_code == LV_EVENT_GESTURE &&  lv_indev_get_gesture_dir(lv_indev_get_act()) == LV_DIR_RIGHT) {
        lv_indev_wait_release(lv_indev_get_act());
        _ui_screen_change(&ui_Screen1, LV_SCR_LOAD_ANIM_NONE, 20, 0, &ui_Screen1_screen_init);
    }
    if(event_code == LV_EVENT_GESTURE &&  lv_indev_get_gesture_dir(lv_indev_get_act()) == LV_DIR_BOTTOM) {
        lv_indev_wait_release(lv_indev_get_act());
        _ui_screen_change(&ui_Screen1, LV_SCR_LOAD_ANIM_NONE, 20, 0, &ui_Screen1_screen_init);
    }
}

// build funtions

void ui_Screen2_screen_init(void)
{
    ui_Screen2 = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_Screen2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_buttonHeart = lv_btn_create(ui_Screen2);
    lv_obj_set_width(ui_buttonHeart, 100);
    lv_obj_set_height(ui_buttonHeart, 50);
    lv_obj_set_x(ui_buttonHeart, 0);
    lv_obj_set_y(ui_buttonHeart, 67);
    lv_obj_set_align(ui_buttonHeart, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_buttonHeart, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_buttonHeart, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_buttonHeart, lv_color_hex(0xFA4040), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_buttonHeart, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_StartMeasure2 = lv_label_create(ui_buttonHeart);
    lv_obj_set_width(ui_StartMeasure2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_StartMeasure2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_StartMeasure2, LV_ALIGN_CENTER);
    lv_label_set_text(ui_StartMeasure2, "Start\nMeasuring");
    lv_obj_set_style_text_align(ui_StartMeasure2, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_heartImg1 = lv_img_create(ui_Screen2);
    lv_img_set_src(ui_heartImg1, &ui_img_208041617);
    lv_obj_set_width(ui_heartImg1, LV_SIZE_CONTENT);   /// 256
    lv_obj_set_height(ui_heartImg1, LV_SIZE_CONTENT);    /// 256
    lv_obj_set_x(ui_heartImg1, -44);
    lv_obj_set_y(ui_heartImg1, -10);
    lv_obj_set_align(ui_heartImg1, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_heartImg1, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_heartImg1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_img_set_zoom(ui_heartImg1, 50);

    ui_heartRateLive = lv_label_create(ui_Screen2);
    lv_obj_set_width(ui_heartRateLive, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_heartRateLive, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_heartRateLive, 28);
    lv_obj_set_y(ui_heartRateLive, -10);
    lv_obj_set_align(ui_heartRateLive, LV_ALIGN_CENTER);
    lv_label_set_text(ui_heartRateLive, "100");
    lv_obj_set_style_text_font(ui_heartRateLive, &lv_font_montserrat_24, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Screen2_Heading = lv_label_create(ui_Screen2);
    lv_obj_set_width(ui_Screen2_Heading, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Screen2_Heading, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Screen2_Heading, 0);
    lv_obj_set_y(ui_Screen2_Heading, -75);
    lv_obj_set_align(ui_Screen2_Heading, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Screen2_Heading, "HEART RATE");
    lv_obj_set_style_text_font(ui_Screen2_Heading, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_add_event_cb(ui_Screen2, ui_event_Screen2, LV_EVENT_ALL, NULL);

}

void ui_Screen2_screen_destroy(void)
{
    if(ui_Screen2) lv_obj_del(ui_Screen2);

    // NULL screen variables
    ui_Screen2 = NULL;
    ui_buttonHeart = NULL;
    ui_StartMeasure2 = NULL;
    ui_heartImg1 = NULL;
    ui_heartRateLive = NULL;
    ui_Screen2_Heading = NULL;

}
