// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.1
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#ifndef UI_SCREEN1_H
#define UI_SCREEN1_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_Screen1
extern void ui_Screen1_screen_init(void);
extern void ui_Screen1_screen_destroy(void);
extern void ui_event_Screen1(lv_event_t * e);
extern lv_obj_t * ui_Screen1;
extern lv_obj_t * ui_time;
extern lv_obj_t * ui_day;
extern lv_obj_t * ui_date;
extern lv_obj_t * ui_heartRateArc;
extern lv_obj_t * ui_lastHeartRate;
extern lv_obj_t * ui_heartImg;
extern lv_obj_t * ui_spO2Arc;
extern lv_obj_t * ui_lastSpO2Value;
extern lv_obj_t * ui_weatherValue;
extern lv_obj_t * ui_lastBodyTempValue;
extern lv_obj_t * ui_lastHumidityValue;
extern lv_obj_t * ui_batteryArc;
extern lv_obj_t * ui_batteryIcon;
extern lv_obj_t * ui_batteryPercentage;
// CUSTOM VARIABLES
extern lv_obj_t * uic_bodyTempValue;

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

