// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.1
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#ifndef UI_SCREEN4_H
#define UI_SCREEN4_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_Screen4
extern void ui_Screen4_screen_init(void);
extern void ui_Screen4_screen_destroy(void);
extern void ui_event_Screen4(lv_event_t * e);
extern lv_obj_t * ui_Screen4;
extern lv_obj_t * ui_buttonBP;
extern lv_obj_t * ui_StartMeasure4;
extern lv_obj_t * ui_HeartImg2;
extern lv_obj_t * ui_heartRateLiveBP;
extern lv_obj_t * ui_Screen4_Heading;
extern lv_obj_t * ui_dia_label;
extern lv_obj_t * ui_sys_label;
extern lv_obj_t * ui_diaLive;
extern lv_obj_t * ui_sysLive;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

