// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.1
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#ifndef UI_SCREEN9_H
#define UI_SCREEN9_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_Screen9
extern void ui_Screen9_screen_init(void);
extern void ui_Screen9_screen_destroy(void);
extern lv_obj_t * ui_Screen9;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

