// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.1
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#include "ui.h"

lv_obj_t * uic_bodyTempValue;
lv_obj_t * ui_Screen1 = NULL;
lv_obj_t * ui_time = NULL;
lv_obj_t * ui_day = NULL;
lv_obj_t * ui_date = NULL;
lv_obj_t * ui_heartRateArc = NULL;
lv_obj_t * ui_lastHeartRate = NULL;
lv_obj_t * ui_heartImg = NULL;
lv_obj_t * ui_spO2Arc = NULL;
lv_obj_t * ui_lastSpO2Value = NULL;
lv_obj_t * ui_weatherValue = NULL;
lv_obj_t * ui_lastBodyTempValue = NULL;
lv_obj_t * ui_lastHumidityValue = NULL;
lv_obj_t * ui_batteryArc = NULL;
lv_obj_t * ui_batteryIcon = NULL;
lv_obj_t * ui_batteryPercentage = NULL;
lv_obj_t * ui_heartRateIndicator = NULL;
lv_obj_t * ui_BPMonitorIndicator = NULL;
lv_obj_t * ui_wifiIndicator = NULL;
lv_obj_t * ui_tempAndHumidityIndicator = NULL;
// event funtions
void ui_event_Screen1(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_GESTURE &&  lv_indev_get_gesture_dir(lv_indev_get_act()) == LV_DIR_TOP) {
        lv_indev_wait_release(lv_indev_get_act());
        _ui_screen_change(&ui_Screen2, LV_SCR_LOAD_ANIM_NONE, 20, 0, &ui_Screen2_screen_init);
    }
    if(event_code == LV_EVENT_GESTURE &&  lv_indev_get_gesture_dir(lv_indev_get_act()) == LV_DIR_BOTTOM) {
        lv_indev_wait_release(lv_indev_get_act());
        _ui_screen_change(&ui_Screen6, LV_SCR_LOAD_ANIM_NONE, 20, 0, &ui_Screen6_screen_init);
    }
}

// build funtions

void ui_Screen1_screen_init(void)
{
    ui_Screen1 = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_Screen1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_time = lv_label_create(ui_Screen1);
    lv_obj_set_width(ui_time, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_time, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_time, 0);
    lv_obj_set_y(ui_time, -4);
    lv_obj_set_align(ui_time, LV_ALIGN_CENTER);
    lv_label_set_text(ui_time, "00:00");
    lv_obj_set_style_text_font(ui_time, &lv_font_montserrat_48, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_day = lv_label_create(ui_Screen1);
    lv_obj_set_width(ui_day, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_day, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_day, -19);
    lv_obj_set_y(ui_day, -38);
    lv_obj_set_align(ui_day, LV_ALIGN_CENTER);
    lv_label_set_text(ui_day, "SUN");
    lv_obj_set_style_text_color(ui_day, lv_color_hex(0x01BAA6), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_day, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_day, &lv_font_montserrat_16, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_date = lv_label_create(ui_Screen1);
    lv_obj_set_width(ui_date, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_date, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_date, 19);
    lv_obj_set_y(ui_date, -38);
    lv_obj_set_align(ui_date, LV_ALIGN_CENTER);
    lv_label_set_text(ui_date, "31");
    lv_obj_set_style_text_color(ui_date, lv_color_hex(0xB0DEFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_date, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_date, &lv_font_montserrat_16, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_heartRateArc = lv_arc_create(ui_Screen1);
    lv_obj_set_width(ui_heartRateArc, 220);
    lv_obj_set_height(ui_heartRateArc, 220);
    lv_obj_set_align(ui_heartRateArc, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_heartRateArc, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_SCROLLABLE |
                      LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM | LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags
    lv_arc_set_range(ui_heartRateArc, 0, 250);
    lv_arc_set_value(ui_heartRateArc, 96);
    lv_arc_set_bg_angles(ui_heartRateArc, 97, 173);
    lv_obj_set_style_arc_color(ui_heartRateArc, lv_color_hex(0x9F2230), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_opa(ui_heartRateArc, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_width(ui_heartRateArc, 10, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_arc_color(ui_heartRateArc, lv_color_hex(0xD90920), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_opa(ui_heartRateArc, 255, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_width(ui_heartRateArc, 10, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_color(ui_heartRateArc, lv_color_hex(0xFFFFFF), LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_heartRateArc, 255, LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_heartRateArc, 0, LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_heartRateArc, 0, LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_heartRateArc, 0, LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_heartRateArc, 0, LV_PART_KNOB | LV_STATE_DEFAULT);

    ui_lastHeartRate = lv_label_create(ui_Screen1);
    lv_obj_set_width(ui_lastHeartRate, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_lastHeartRate, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_lastHeartRate, -57);
    lv_obj_set_y(ui_lastHeartRate, 71);
    lv_obj_set_align(ui_lastHeartRate, LV_ALIGN_CENTER);
    lv_label_set_text(ui_lastHeartRate, "96");
    lv_obj_set_style_text_font(ui_lastHeartRate, &lv_font_montserrat_12, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_heartImg = lv_img_create(ui_Screen1);
    lv_img_set_src(ui_heartImg, &ui_img_208041617);
    lv_obj_set_width(ui_heartImg, LV_SIZE_CONTENT);   /// 256
    lv_obj_set_height(ui_heartImg, LV_SIZE_CONTENT);    /// 256
    lv_obj_set_x(ui_heartImg, 0);
    lv_obj_set_y(ui_heartImg, 105);
    lv_obj_set_align(ui_heartImg, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_heartImg, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_heartImg, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_img_set_zoom(ui_heartImg, 13);

    ui_spO2Arc = lv_arc_create(ui_Screen1);
    lv_obj_set_width(ui_spO2Arc, 220);
    lv_obj_set_height(ui_spO2Arc, 220);
    lv_obj_set_align(ui_spO2Arc, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_spO2Arc, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_SCROLLABLE |
                      LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM | LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags
    lv_arc_set_value(ui_spO2Arc, 85);
    lv_arc_set_bg_angles(ui_spO2Arc, 187, 263);
    lv_obj_set_style_arc_width(ui_spO2Arc, 10, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_arc_color(ui_spO2Arc, lv_color_hex(0x15D800), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_opa(ui_spO2Arc, 255, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_width(ui_spO2Arc, 10, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_color(ui_spO2Arc, lv_color_hex(0xFFFFFF), LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_spO2Arc, 0, LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_spO2Arc, 0, LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_spO2Arc, 0, LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_spO2Arc, 0, LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_spO2Arc, 0, LV_PART_KNOB | LV_STATE_DEFAULT);

    ui_lastSpO2Value = lv_label_create(ui_Screen1);
    lv_obj_set_width(ui_lastSpO2Value, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_lastSpO2Value, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_lastSpO2Value, -28);
    lv_obj_set_y(ui_lastSpO2Value, -84);
    lv_obj_set_align(ui_lastSpO2Value, LV_ALIGN_CENTER);
    lv_label_set_text(ui_lastSpO2Value, "85");
    lv_obj_set_style_text_font(ui_lastSpO2Value, &lv_font_montserrat_12, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_weatherValue = lv_label_create(ui_Screen1);
    lv_obj_set_width(ui_weatherValue, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_weatherValue, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_weatherValue, -40);
    lv_obj_set_y(ui_weatherValue, 54);
    lv_obj_set_align(ui_weatherValue, LV_ALIGN_CENTER);
    lv_label_set_text(ui_weatherValue, "30°C");
    lv_obj_set_style_text_font(ui_weatherValue, &lv_font_montserrat_10, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_lastBodyTempValue = lv_label_create(ui_Screen1);
    lv_obj_set_width(ui_lastBodyTempValue, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_lastBodyTempValue, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_lastBodyTempValue, 0);
    lv_obj_set_y(ui_lastBodyTempValue, 54);
    lv_obj_set_align(ui_lastBodyTempValue, LV_ALIGN_CENTER);
    lv_label_set_text(ui_lastBodyTempValue, "37°C");
    lv_obj_set_style_text_font(ui_lastBodyTempValue, &lv_font_montserrat_10, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_lastHumidityValue = lv_label_create(ui_Screen1);
    lv_obj_set_width(ui_lastHumidityValue, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_lastHumidityValue, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_lastHumidityValue, 40);
    lv_obj_set_y(ui_lastHumidityValue, 54);
    lv_obj_set_align(ui_lastHumidityValue, LV_ALIGN_CENTER);
    lv_label_set_text(ui_lastHumidityValue, "65%");
    lv_obj_set_style_text_font(ui_lastHumidityValue, &lv_font_montserrat_10, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_batteryArc = lv_arc_create(ui_Screen1);
    lv_obj_set_width(ui_batteryArc, 220);
    lv_obj_set_height(ui_batteryArc, 220);
    lv_obj_set_align(ui_batteryArc, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_batteryArc, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_SCROLLABLE |
                      LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM | LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags
    lv_arc_set_value(ui_batteryArc, 55);
    lv_arc_set_bg_angles(ui_batteryArc, 277, 0);
    lv_obj_set_style_arc_width(ui_batteryArc, 10, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_arc_color(ui_batteryArc, lv_color_hex(0x009EFC), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_opa(ui_batteryArc, 255, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_width(ui_batteryArc, 10, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_color(ui_batteryArc, lv_color_hex(0xFFFFFF), LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_batteryArc, 0, LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_batteryArc, 0, LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_batteryArc, 0, LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_batteryArc, 0, LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_batteryArc, 0, LV_PART_KNOB | LV_STATE_DEFAULT);

    ui_batteryIcon = lv_img_create(ui_Screen1);
    lv_obj_set_width(ui_batteryIcon, LV_SIZE_CONTENT);   /// 1600
    lv_obj_set_height(ui_batteryIcon, LV_SIZE_CONTENT);    /// 1600
    lv_obj_set_x(ui_batteryIcon, 0);
    lv_obj_set_y(ui_batteryIcon, -108);
    lv_obj_set_align(ui_batteryIcon, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_batteryIcon, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_batteryIcon, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_img_set_zoom(ui_batteryIcon, 3);

    ui_batteryPercentage = lv_label_create(ui_Screen1);
    lv_obj_set_width(ui_batteryPercentage, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_batteryPercentage, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_batteryPercentage, 70);
    lv_obj_set_y(ui_batteryPercentage, -56);
    lv_obj_set_align(ui_batteryPercentage, LV_ALIGN_CENTER);
    lv_label_set_text(ui_batteryPercentage, "55");
    lv_obj_set_style_text_font(ui_batteryPercentage, &lv_font_montserrat_12, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_heartRateIndicator = lv_img_create(ui_Screen1);
    lv_img_set_src(ui_heartRateIndicator, &ui_img_208041617);
    lv_obj_set_width(ui_heartRateIndicator, LV_SIZE_CONTENT);   /// 256
    lv_obj_set_height(ui_heartRateIndicator, LV_SIZE_CONTENT);    /// 256
    lv_obj_set_x(ui_heartRateIndicator, 45);
    lv_obj_set_y(ui_heartRateIndicator, 94);
    lv_obj_set_align(ui_heartRateIndicator, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_heartRateIndicator, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_heartRateIndicator, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_img_set_zoom(ui_heartRateIndicator, 13);

    ui_BPMonitorIndicator = lv_img_create(ui_Screen1);
    lv_img_set_src(ui_BPMonitorIndicator, &ui_img_208041617);
    lv_obj_set_width(ui_BPMonitorIndicator, LV_SIZE_CONTENT);   /// 256
    lv_obj_set_height(ui_BPMonitorIndicator, LV_SIZE_CONTENT);    /// 256
    lv_obj_set_x(ui_BPMonitorIndicator, 84);
    lv_obj_set_y(ui_BPMonitorIndicator, 63);
    lv_obj_set_align(ui_BPMonitorIndicator, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_BPMonitorIndicator, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_BPMonitorIndicator, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_img_set_zoom(ui_BPMonitorIndicator, 13);

    ui_wifiIndicator = lv_img_create(ui_Screen1);
    lv_img_set_src(ui_wifiIndicator, &ui_img_208041617);
    lv_obj_set_width(ui_wifiIndicator, LV_SIZE_CONTENT);   /// 256
    lv_obj_set_height(ui_wifiIndicator, LV_SIZE_CONTENT);    /// 256
    lv_obj_set_x(ui_wifiIndicator, 66);
    lv_obj_set_y(ui_wifiIndicator, 81);
    lv_obj_set_align(ui_wifiIndicator, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_wifiIndicator, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_wifiIndicator, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_img_set_zoom(ui_wifiIndicator, 13);

    ui_tempAndHumidityIndicator = lv_img_create(ui_Screen1);
    lv_img_set_src(ui_tempAndHumidityIndicator, &ui_img_208041617);
    lv_obj_set_width(ui_tempAndHumidityIndicator, LV_SIZE_CONTENT);   /// 256
    lv_obj_set_height(ui_tempAndHumidityIndicator, LV_SIZE_CONTENT);    /// 256
    lv_obj_set_x(ui_tempAndHumidityIndicator, 99);
    lv_obj_set_y(ui_tempAndHumidityIndicator, 39);
    lv_obj_set_align(ui_tempAndHumidityIndicator, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_tempAndHumidityIndicator, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_tempAndHumidityIndicator, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_img_set_zoom(ui_tempAndHumidityIndicator, 13);

    lv_obj_add_event_cb(ui_Screen1, ui_event_Screen1, LV_EVENT_ALL, NULL);
    uic_bodyTempValue = ui_lastBodyTempValue;

}

void ui_Screen1_screen_destroy(void)
{
    if(ui_Screen1) lv_obj_del(ui_Screen1);

    // NULL screen variables
    ui_Screen1 = NULL;
    ui_time = NULL;
    ui_day = NULL;
    ui_date = NULL;
    ui_heartRateArc = NULL;
    ui_lastHeartRate = NULL;
    ui_heartImg = NULL;
    ui_spO2Arc = NULL;
    ui_lastSpO2Value = NULL;
    ui_weatherValue = NULL;
    uic_bodyTempValue = NULL;
    ui_lastBodyTempValue = NULL;
    ui_lastHumidityValue = NULL;
    ui_batteryArc = NULL;
    ui_batteryIcon = NULL;
    ui_batteryPercentage = NULL;
    ui_heartRateIndicator = NULL;
    ui_BPMonitorIndicator = NULL;
    ui_wifiIndicator = NULL;
    ui_tempAndHumidityIndicator = NULL;

}
