// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.1
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#include "ui.h"

lv_obj_t * ui_Screen9 = NULL;
// event funtions

// build funtions

void ui_Screen9_screen_init(void)
{
    ui_Screen9 = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_Screen9, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

}

void ui_Screen9_screen_destroy(void)
{
    if(ui_Screen9) lv_obj_del(ui_Screen9);

    // NULL screen variables
    ui_Screen9 = NULL;

}
