// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.1
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#ifndef UI_SCREEN5_H
#define UI_SCREEN5_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_Screen5
extern void ui_Screen5_screen_init(void);
extern void ui_Screen5_screen_destroy(void);
extern void ui_event_Screen5(lv_event_t * e);
extern lv_obj_t * ui_Screen5;
extern lv_obj_t * ui_buttonTemp;
extern lv_obj_t * ui_StartMeasure5;
extern lv_obj_t * ui_humLive;
extern lv_obj_t * ui_Screen5_Heading;
extern lv_obj_t * ui_temp_label;
extern lv_obj_t * ui_hum_label;
extern lv_obj_t * ui_tempLive;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

