// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.1
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#ifndef UI_SCREEN6_H
#define UI_SCREEN6_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_Screen6
extern void ui_Screen6_screen_init(void);
extern void ui_Screen6_screen_destroy(void);
extern void ui_event_Screen6(lv_event_t * e);
extern lv_obj_t * ui_Screen6;
extern lv_obj_t * ui_wifiSwitch;
extern lv_obj_t * ui_bleSwitch;
extern lv_obj_t * ui_ButtonSyncNow;
extern lv_obj_t * ui_SyncNowText;
extern void ui_event_ButtonUpgrade(lv_event_t * e);
extern lv_obj_t * ui_ButtonUpgrade;
extern lv_obj_t * ui_UpgradeText;
extern lv_obj_t * ui_WIFI;
extern lv_obj_t * ui_BLUETOOTH;
extern lv_obj_t * ui_Slider1;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

